project:
  type: website
  output-dir: docs
  
website:
  title: "Gretchen Bahmueller"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/gretchenbahmueller/MyWebsite.git 
      - icon: linkedin
        href: https://linkedin.com/in/gretchen-bahmueller-0b5a7b278
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Gretchen Bahmueller"

format:
  html:
    theme: quartz
    toc: true

editor: source

